services:
  dev-kitu-logic-processor:
    container_name: dev-kitu-logic-processor
    build: .
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    ports:
      - "4000:4000"
    command: cargo watch # keep the container running, to remote debug inside the container
    # command: cargo watch -x build -x 'test -- --nocapture' # if won't remote debug, use this command
