version: '3.8'
services:
  dev-kitu-logic-processor:
    build: ./kitu-logic-processor
    volumes:
      - ./kitu-logic-processor:/usr/src/kitu-logic-processor
    ports:
      - "4000:4000"
    command: cargo watch -x run
