services:
  dev-kitu-logic-processor:
    container_name: dev-kitu-logic-processor
    build: .
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    ports:
      - "4000:4000"
    command: cargo watch -x build
    # command: cargo watch -x build -x test
