import type { AdminClient } from './create-admin-client.js';
export declare function setAdminClientContext(client: AdminClient): {
    subscribe: (this: void, run: import("svelte/store").Subscriber<{
        connectionState: import("./types.js").ConnectionState;
        worldSnapshot: import("./types.js").WorldSnapshot;
        debugLogs: import("./types.js").DebugLogEntry[];
        lastError: string | null;
        appActionCatalog: import("./types.js").AppActionCatalog;
        webTransportState: import("./types.js").WebTransportState;
        webTransportDetail: string | null;
        lastOscSendStatus: import("./types.js").OscSendStatus;
        objectCount: number;
    }>, invalidate?: () => void) => import("svelte/store").Unsubscriber;
    options: Readonly<{
        apiUrl: string;
        webSocketUrl: string;
        webTransportUrl?: string;
        webTransportCertificateSha256?: string;
        kepRoute?: string;
        reconnectDelayMs?: number;
        fetch?: typeof globalThis.fetch;
        createWebSocket?: (url: string) => import("./types.js").WebSocketLike;
        createWebTransport?: (url: string, certificateSha256?: Uint8Array) => import("./types.js").WebTransportSessionLike;
        isBrowser?: boolean;
    }>;
    apiBaseUrl: () => string;
    request: (path: string, init?: RequestInit) => Promise<Response>;
    start: () => void;
    stop: () => void;
    sendOsc: (payload: import("./types.js").ClientOscMessage) => boolean;
    loadAppActions: () => Promise<import("./types.js").AppActionCatalog | null>;
    runAppAction: (actionId: string, inputs: Record<string, import("./types.js").ActionValue>) => Promise<boolean>;
    spawnObject: (kind: string, x: number, y: number, z: number) => Promise<boolean>;
    moveObject: (id: string, x: number, y: number, z: number) => Promise<boolean>;
    resetWorld: () => Promise<boolean>;
    applyServerEvent: (event: import("./types.js").ServerEvent) => void;
    connectionState: import("svelte/store").Writable<import("./types.js").ConnectionState>;
    worldSnapshot: import("svelte/store").Writable<import("./types.js").WorldSnapshot>;
    debugLogs: import("svelte/store").Writable<import("./types.js").DebugLogEntry[]>;
    lastError: import("svelte/store").Writable<string | null>;
    appActionCatalog: import("svelte/store").Writable<import("./types.js").AppActionCatalog>;
    webTransportState: import("svelte/store").Writable<import("./types.js").WebTransportState>;
    webTransportDetail: import("svelte/store").Writable<string | null>;
    lastOscSendStatus: import("svelte/store").Writable<import("./types.js").OscSendStatus>;
    objectCount: import("svelte/store").Readable<number>;
};
export declare function getAdminClient(): {
    subscribe: (this: void, run: import("svelte/store").Subscriber<{
        connectionState: import("./types.js").ConnectionState;
        worldSnapshot: import("./types.js").WorldSnapshot;
        debugLogs: import("./types.js").DebugLogEntry[];
        lastError: string | null;
        appActionCatalog: import("./types.js").AppActionCatalog;
        webTransportState: import("./types.js").WebTransportState;
        webTransportDetail: string | null;
        lastOscSendStatus: import("./types.js").OscSendStatus;
        objectCount: number;
    }>, invalidate?: () => void) => import("svelte/store").Unsubscriber;
    options: Readonly<{
        apiUrl: string;
        webSocketUrl: string;
        webTransportUrl?: string;
        webTransportCertificateSha256?: string;
        kepRoute?: string;
        reconnectDelayMs?: number;
        fetch?: typeof globalThis.fetch;
        createWebSocket?: (url: string) => import("./types.js").WebSocketLike;
        createWebTransport?: (url: string, certificateSha256?: Uint8Array) => import("./types.js").WebTransportSessionLike;
        isBrowser?: boolean;
    }>;
    apiBaseUrl: () => string;
    request: (path: string, init?: RequestInit) => Promise<Response>;
    start: () => void;
    stop: () => void;
    sendOsc: (payload: import("./types.js").ClientOscMessage) => boolean;
    loadAppActions: () => Promise<import("./types.js").AppActionCatalog | null>;
    runAppAction: (actionId: string, inputs: Record<string, import("./types.js").ActionValue>) => Promise<boolean>;
    spawnObject: (kind: string, x: number, y: number, z: number) => Promise<boolean>;
    moveObject: (id: string, x: number, y: number, z: number) => Promise<boolean>;
    resetWorld: () => Promise<boolean>;
    applyServerEvent: (event: import("./types.js").ServerEvent) => void;
    connectionState: import("svelte/store").Writable<import("./types.js").ConnectionState>;
    worldSnapshot: import("svelte/store").Writable<import("./types.js").WorldSnapshot>;
    debugLogs: import("svelte/store").Writable<import("./types.js").DebugLogEntry[]>;
    lastError: import("svelte/store").Writable<string | null>;
    appActionCatalog: import("svelte/store").Writable<import("./types.js").AppActionCatalog>;
    webTransportState: import("svelte/store").Writable<import("./types.js").WebTransportState>;
    webTransportDetail: import("svelte/store").Writable<string | null>;
    lastOscSendStatus: import("svelte/store").Writable<import("./types.js").OscSendStatus>;
    objectCount: import("svelte/store").Readable<number>;
};
