import type { ActionValue, AdminClientOptions, AppActionCatalog, ClientOscMessage, ConnectionState, DebugLogEntry, OscSendStatus, ServerEvent, WebSocketLike, WebTransportState, WorldSnapshot } from './types.js';
export declare function createAdminClient(input: AdminClientOptions): {
    subscribe: (this: void, run: import("svelte/store").Subscriber<{
        connectionState: ConnectionState;
        worldSnapshot: WorldSnapshot;
        debugLogs: DebugLogEntry[];
        lastError: string | null;
        appActionCatalog: AppActionCatalog;
        webTransportState: WebTransportState;
        webTransportDetail: string | null;
        lastOscSendStatus: OscSendStatus;
        objectCount: number;
    }>, invalidate?: () => void) => import("svelte/store").Unsubscriber;
    options: Readonly<{
        apiUrl: string;
        webSocketUrl: string;
        webTransportUrl?: string;
        webTransportCertificateSha256?: string;
        kepRoute?: string;
        reconnectDelayMs?: number;
        fetch?: typeof globalThis.fetch;
        createWebSocket?: (url: string) => WebSocketLike;
        createWebTransport?: (url: string, certificateSha256?: Uint8Array) => import("./types.js").WebTransportSessionLike;
        isBrowser?: boolean;
    }>;
    apiBaseUrl: () => string;
    request: (path: string, init?: RequestInit) => Promise<Response>;
    start: () => void;
    stop: () => void;
    sendOsc: (payload: ClientOscMessage) => boolean;
    loadAppActions: () => Promise<AppActionCatalog | null>;
    runAppAction: (actionId: string, inputs: Record<string, ActionValue>) => Promise<boolean>;
    spawnObject: (kind: string, x: number, y: number, z: number) => Promise<boolean>;
    moveObject: (id: string, x: number, y: number, z: number) => Promise<boolean>;
    resetWorld: () => Promise<boolean>;
    applyServerEvent: (event: ServerEvent) => void;
    connectionState: import("svelte/store").Writable<ConnectionState>;
    worldSnapshot: import("svelte/store").Writable<WorldSnapshot>;
    debugLogs: import("svelte/store").Writable<DebugLogEntry[]>;
    lastError: import("svelte/store").Writable<string | null>;
    appActionCatalog: import("svelte/store").Writable<AppActionCatalog>;
    webTransportState: import("svelte/store").Writable<WebTransportState>;
    webTransportDetail: import("svelte/store").Writable<string | null>;
    lastOscSendStatus: import("svelte/store").Writable<OscSendStatus>;
    objectCount: import("svelte/store").Readable<number>;
};
export type AdminClient = ReturnType<typeof createAdminClient>;
